proxies:
  - http://proxy1.example.com:8080
  - http://proxy2.example.com:8080
  - socks5://proxy3.example.com:1080

user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"

scholar_url: "https://scholar.google.com"

captcha_solver:
  enabled: true
  service: "local-ocr"  # Options: 'local-ocr', '2captcha', 'anticaptcha'
  api_key: "your-api-key-here"

retry_attempts: 3
retry_delay: 5  # in seconds

logging:
  level: "INFO"
  file: "scraper.log"
